package model;
// Generated 28 déc. 2019 21:54:00 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Aliment generated by hbm2java
 */
@Entity
@Table(name="aliment"
    ,catalog="volailledor"
)
public class Aliment  implements java.io.Serializable {


     private int idAli;
     private String nomAli;
     private String description;
     private BigDecimal prix;

    public Aliment() {
    }

    public Aliment(int idAli, String nomAli, String description, BigDecimal prix) {
       this.idAli = idAli;
       this.nomAli = nomAli;
       this.description = description;
       this.prix = prix;
    }
   
     @Id 

    
    @Column(name="idAli", unique=true, nullable=false)
    public int getIdAli() {
        return this.idAli;
    }
    
    public void setIdAli(int idAli) {
        this.idAli = idAli;
    }

    
    @Column(name="nomAli", nullable=false, length=15)
    public String getNomAli() {
        return this.nomAli;
    }
    
    public void setNomAli(String nomAli) {
        this.nomAli = nomAli;
    }

    
    @Column(name="description", nullable=false, length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="prix", nullable=false, precision=8)
    public BigDecimal getPrix() {
        return this.prix;
    }
    
    public void setPrix(BigDecimal prix) {
        this.prix = prix;
    }




}


