package model;
// Generated 28 déc. 2019 21:54:00 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name="client"
    ,catalog="volailledor"
)
public class Client  implements java.io.Serializable {


     private int idClient;
     private String adresse;
     private Integer tel;

    public Client() {
    }

	
    public Client(int idClient) {
        this.idClient = idClient;
    }
    public Client(int idClient, String adresse, Integer tel) {
       this.idClient = idClient;
       this.adresse = adresse;
       this.tel = tel;
    }
   
     @Id 

    
    @Column(name="idClient", unique=true, nullable=false)
    public int getIdClient() {
        return this.idClient;
    }
    
    public void setIdClient(int idClient) {
        this.idClient = idClient;
    }

    
    @Column(name="adresse", length=15)
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    
    @Column(name="tel")
    public Integer getTel() {
        return this.tel;
    }
    
    public void setTel(Integer tel) {
        this.tel = tel;
    }




}


