package model;
// Generated 28 déc. 2019 21:54:00 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Maladie generated by hbm2java
 */
@Entity
@Table(name="maladie"
    ,catalog="volailledor"
)
public class Maladie  implements java.io.Serializable {


     private int idM;
     private String nomM;
     private String descriptionTraitement;
     private String descriptionMaladie;
     private String duree;

    public Maladie() {
    }

	
    public Maladie(int idM, String nomM) {
        this.idM = idM;
        this.nomM = nomM;
    }
    public Maladie(int idM, String nomM, String descriptionTraitement, String descriptionMaladie, String duree) {
       this.idM = idM;
       this.nomM = nomM;
       this.descriptionTraitement = descriptionTraitement;
       this.descriptionMaladie = descriptionMaladie;
       this.duree = duree;
    }
   
     @Id 

    
    @Column(name="idM", unique=true, nullable=false)
    public int getIdM() {
        return this.idM;
    }
    
    public void setIdM(int idM) {
        this.idM = idM;
    }

    
    @Column(name="nomM", nullable=false, length=20)
    public String getNomM() {
        return this.nomM;
    }
    
    public void setNomM(String nomM) {
        this.nomM = nomM;
    }

    
    @Column(name="descriptionTraitement", length=65535)
    public String getDescriptionTraitement() {
        return this.descriptionTraitement;
    }
    
    public void setDescriptionTraitement(String descriptionTraitement) {
        this.descriptionTraitement = descriptionTraitement;
    }

    
    @Column(name="descriptionMaladie", length=65535)
    public String getDescriptionMaladie() {
        return this.descriptionMaladie;
    }
    
    public void setDescriptionMaladie(String descriptionMaladie) {
        this.descriptionMaladie = descriptionMaladie;
    }

    
    @Column(name="duree", length=10)
    public String getDuree() {
        return this.duree;
    }
    
    public void setDuree(String duree) {
        this.duree = duree;
    }




}


