package model;
// Generated 28 déc. 2019 21:54:00 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Race generated by hbm2java
 */
@Entity
@Table(name="race"
    ,catalog="volailledor"
)
public class Race  implements java.io.Serializable {


     private int idRace;
     private String nom;
     private String description;
     private BigDecimal prixRace;

    public Race() {
    }

	
    public Race(int idRace, String nom, String description) {
        this.idRace = idRace;
        this.nom = nom;
        this.description = description;
    }
    public Race(int idRace, String nom, String description, BigDecimal prixRace) {
       this.idRace = idRace;
       this.nom = nom;
       this.description = description;
       this.prixRace = prixRace;
    }
   
     @Id 

    
    @Column(name="idRace", unique=true, nullable=false)
    public int getIdRace() {
        return this.idRace;
    }
    
    public void setIdRace(int idRace) {
        this.idRace = idRace;
    }

    
    @Column(name="nom", nullable=false, length=15)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="description", nullable=false, length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="prix_race", precision=7)
    public BigDecimal getPrixRace() {
        return this.prixRace;
    }
    
    public void setPrixRace(BigDecimal prixRace) {
        this.prixRace = prixRace;
    }




}


