package model;
// Generated 28 déc. 2019 21:54:00 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Typeoeuf generated by hbm2java
 */
@Entity
@Table(name="typeoeuf"
    ,catalog="volailledor"
)
public class Typeoeuf  implements java.io.Serializable {


     private int idTypeOeuf;
     private String nomTf;
     private BigDecimal prixAlveole;

    public Typeoeuf() {
    }

	
    public Typeoeuf(int idTypeOeuf) {
        this.idTypeOeuf = idTypeOeuf;
    }
    public Typeoeuf(int idTypeOeuf, String nomTf, BigDecimal prixAlveole) {
       this.idTypeOeuf = idTypeOeuf;
       this.nomTf = nomTf;
       this.prixAlveole = prixAlveole;
    }
   
     @Id 

    
    @Column(name="idTypeOeuf", unique=true, nullable=false)
    public int getIdTypeOeuf() {
        return this.idTypeOeuf;
    }
    
    public void setIdTypeOeuf(int idTypeOeuf) {
        this.idTypeOeuf = idTypeOeuf;
    }

    
    @Column(name="nomTf", length=10)
    public String getNomTf() {
        return this.nomTf;
    }
    
    public void setNomTf(String nomTf) {
        this.nomTf = nomTf;
    }

    
    @Column(name="prix_alveole", precision=9)
    public BigDecimal getPrixAlveole() {
        return this.prixAlveole;
    }
    
    public void setPrixAlveole(BigDecimal prixAlveole) {
        this.prixAlveole = prixAlveole;
    }




}


