package model;
// Generated 28 déc. 2019 21:54:00 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Vaccin generated by hbm2java
 */
@Entity
@Table(name="vaccin"
    ,catalog="volailledor"
)
public class Vaccin  implements java.io.Serializable {


     private int idVac;
     private String nomVac;
     private String periode;
     private int qteVac;
     private int qtePoule;
     private String description;
     private BigDecimal prix;

    public Vaccin() {
    }

	
    public Vaccin(int idVac, String nomVac, String periode, int qteVac, int qtePoule) {
        this.idVac = idVac;
        this.nomVac = nomVac;
        this.periode = periode;
        this.qteVac = qteVac;
        this.qtePoule = qtePoule;
    }
    public Vaccin(int idVac, String nomVac, String periode, int qteVac, int qtePoule, String description, BigDecimal prix) {
       this.idVac = idVac;
       this.nomVac = nomVac;
       this.periode = periode;
       this.qteVac = qteVac;
       this.qtePoule = qtePoule;
       this.description = description;
       this.prix = prix;
    }
   
     @Id 

    
    @Column(name="idVac", unique=true, nullable=false)
    public int getIdVac() {
        return this.idVac;
    }
    
    public void setIdVac(int idVac) {
        this.idVac = idVac;
    }

    
    @Column(name="nomVac", nullable=false, length=15)
    public String getNomVac() {
        return this.nomVac;
    }
    
    public void setNomVac(String nomVac) {
        this.nomVac = nomVac;
    }

    
    @Column(name="periode", nullable=false, length=15)
    public String getPeriode() {
        return this.periode;
    }
    
    public void setPeriode(String periode) {
        this.periode = periode;
    }

    
    @Column(name="qteVac", nullable=false)
    public int getQteVac() {
        return this.qteVac;
    }
    
    public void setQteVac(int qteVac) {
        this.qteVac = qteVac;
    }

    
    @Column(name="qtePoule", nullable=false)
    public int getQtePoule() {
        return this.qtePoule;
    }
    
    public void setQtePoule(int qtePoule) {
        this.qtePoule = qtePoule;
    }

    
    @Column(name="description", length=200)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="prix", precision=8)
    public BigDecimal getPrix() {
        return this.prix;
    }
    
    public void setPrix(BigDecimal prix) {
        this.prix = prix;
    }




}


