package app.modules.model;
// Generated 29 déc. 2019 10:37:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Batiment generated by hbm2java
 */
@Entity
@Table(name="batiment"
    ,catalog="volailledor"
)
public class Batiment  implements java.io.Serializable {


     private int idBat;
     private BigDecimal surface;
     private String nomBat;

    public Batiment() {
    }

    public Batiment(int idBat, BigDecimal surface, String nomBat) {
       this.idBat = idBat;
       this.surface = surface;
       this.nomBat = nomBat;
    }
   
     @Id 

    
    @Column(name="idBat", unique=true, nullable=false)
    public int getIdBat() {
        return this.idBat;
    }
    
    public void setIdBat(int idBat) {
        this.idBat = idBat;
    }

    
    @Column(name="surface", nullable=false, precision=5)
    public BigDecimal getSurface() {
        return this.surface;
    }
    
    public void setSurface(BigDecimal surface) {
        this.surface = surface;
    }

    
    @Column(name="nomBat", nullable=false, length=10)
    public String getNomBat() {
        return this.nomBat;
    }
    
    public void setNomBat(String nomBat) {
        this.nomBat = nomBat;
    }




}


