package app.modules.model;
// Generated 29 déc. 2019 10:37:43 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Fournisseur generated by hbm2java
 */
@Entity
@Table(name="fournisseur"
    ,catalog="volailledor"
    , uniqueConstraints = @UniqueConstraint(columnNames="email") 
)
public class Fournisseur  implements java.io.Serializable {


     private int idFourn;
     private String nomFourn;
     private String adresse;
     private int tel;
     private String email;
     private String siteweb;
     private Integer typeFourn;

    public Fournisseur() {
    }

	
    public Fournisseur(int idFourn, String nomFourn, String adresse, int tel) {
        this.idFourn = idFourn;
        this.nomFourn = nomFourn;
        this.adresse = adresse;
        this.tel = tel;
    }
    public Fournisseur(int idFourn, String nomFourn, String adresse, int tel, String email, String siteweb, Integer typeFourn) {
       this.idFourn = idFourn;
       this.nomFourn = nomFourn;
       this.adresse = adresse;
       this.tel = tel;
       this.email = email;
       this.siteweb = siteweb;
       this.typeFourn = typeFourn;
    }
   
     @Id 

    
    @Column(name="idFourn", unique=true, nullable=false)
    public int getIdFourn() {
        return this.idFourn;
    }
    
    public void setIdFourn(int idFourn) {
        this.idFourn = idFourn;
    }

    
    @Column(name="nomFourn", nullable=false, length=20)
    public String getNomFourn() {
        return this.nomFourn;
    }
    
    public void setNomFourn(String nomFourn) {
        this.nomFourn = nomFourn;
    }

    
    @Column(name="adresse", nullable=false, length=20)
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    
    @Column(name="tel", nullable=false)
    public int getTel() {
        return this.tel;
    }
    
    public void setTel(int tel) {
        this.tel = tel;
    }

    
    @Column(name="email", unique=true, length=20)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="siteweb", length=20)
    public String getSiteweb() {
        return this.siteweb;
    }
    
    public void setSiteweb(String siteweb) {
        this.siteweb = siteweb;
    }

    
    @Column(name="typeFourn")
    public Integer getTypeFourn() {
        return this.typeFourn;
    }
    
    public void setTypeFourn(Integer typeFourn) {
        this.typeFourn = typeFourn;
    }




}


